name: MooIE6Update
author: arieh
category: Utilities
tags: [ie6, miscellaneous, "Internet Explorer", interface] 
demo: http://arieh.github.com/MooIE6Update/
docs: http://moodocs.net/arieh/moo-ie6-update/IENotifier
current: 1.3.1